name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
    - name: Update project website
      run: eval $(ssh-agent -s -t 600)                           ➀
        ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")      ➁
        git config --global user.email "rmack005@odu.edu"      ➂
        git config --global user.name "Project Actions"
        ./gradlew deployWebsite  